### ISSUE TITLE
Session not disconnected after a password change resulting in an Exception.

### ISSUE THREAD

**Issue by SullivanDaly** [vaticle/typedb-console#200]
## Description

After changing the password of the account you are logged with, I was not disconnected and still had access to the console.
Doing so, when I tried to change my password a second time, I got a StatusRuntimeException.

## Environment

1. OS (where TypeDB server runs): GCP Instance
2. TypeDB version (and platform): 
3. TypeDB client: TypeDB Console 2.16.1
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Log with an account
`typedb console --cluster=1.2.3.4:1729 --username=fakeUser --password=fakePaswd`
Change the password
`user password fakeUser`
Enter your newpassword
`Password: ************`
Change your password again
`user password fakeUser`
Enter second new password
`Password: ************`

## Expected Output

After entering the first password:
`Updated password for user 'fakeUser'. Please loggin again with your new updated password.`

## Actual Output

After the second password change:
`Exception in thread "main" io.grpc.StatusRuntimeException: UNAUTHENTICATED: [CLS07] Server Error: Invalid password credential.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.vaticle.typedb.protocol.TypeDBClusterGrpc$TypeDBClusterBlockingStub.userToken(TypeDBClusterGrpc.java:775)
	at com.vaticle.typedb.client.connection.cluster.ClusterServerStub.mayRenewToken(ClusterServerStub.java:208)
	at com.vaticle.typedb.client.connection.cluster.ClusterServerStub.usersPasswordSet(ClusterServerStub.java:123)
	at com.vaticle.typedb.client.connection.cluster.ClusterUserManager.lambda$passwordSet$6(ClusterUserManager.java:108)
	at com.vaticle.typedb.client.connection.cluster.ClusterClient$1.run(ClusterClient.java:175)
	at com.vaticle.typedb.client.connection.cluster.ClusterClient$FailsafeTask.runPrimaryReplica(ClusterClient.java:234)
	at com.vaticle.typedb.client.connection.cluster.ClusterUserManager.passwordSet(ClusterUserManager.java:112)
	at com.vaticle.typedb.console.TypeDBConsole.runUserPassword(TypeDBConsole.java:512)
	at com.vaticle.typedb.console.TypeDBConsole.runREPLMode(TypeDBConsole.java:199)
	at com.vaticle.typedb.console.TypeDBConsole.main(TypeDBConsole.java:126)`
 
## Additional information

Adding password confirmation would also be a good idea maybe.

**Comment by flyingsilverfin** [comment]
@jamesreprise can you take a look soon please?
